[profiles.user]
user_id = "@proycon:matrix.anaproy.nl"

[settings.image_preview]
protocol.type = "sixel"

[settings.notifications]
enabled = true

[settings]
username_display = "displayname"

[settings.sort]
rooms = ["unread","name"]

[macros.normal]
"go" = ":open<Enter>"
"gc" = ":chats<Enter>"
"gr" = ":rooms<Enter>"
"gd" = ":dms<Enter>"
"gu" = ":unreads<Enter>"
"gU" = ":unreads clear<Enter>"


