[colors.bright]
black = "0x928374"
blue = "0x8fb1a4"
cyan = "0x9fd18c"
green = "0xc5dc85"
magenta = "0xe799ae"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfbbe30"

[colors.normal]
black = "0x282828"
blue = "0x508a8d"
cyan = "0x689d6a"
green = "0xb5bd68"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x17191a"
bright_foreground = "0xffffff"
dim_foreground = "0x9a9a9a"
foreground = "0xebdbb2"

[colors.selection]
background = "0x003300"
text = "0x00ff00"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Monospace"
style = "Bold"

[font.bold_italic]
family = "Monospace"
style = "Bold Italic"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super|Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Super|Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Super"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super|Shift"

#[mouse.hints.launcher]
#program = "xdg-open"

[window]
dynamic_title = true
opacity = 0.95
