#!/bin/sh
while read file
do
	fullpath="$(pwd)/$file"
    case "$1" in
        "w")
            feh --bg-scale "$fullpath"
            ;;
        "n")
            cp "$file" "/nettmp" && notify-send -i "$fullpath" "$file copied to /nettmp." &
            ;;
        "t")
            cp "$file" "/tmp" && notify-send -i "$fullpath" "$file copied to /tmp." &
            ;;
        "c")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.bmdirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            cp "$file" "$destdir" && notify-send -i "$fullpath" "$file copied to $destdir." &
            ;;
        "m")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.bmdirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            cp "$file" "$destdir" && notify-send -i "$fullpath" "$file moved to $destdir." &
            ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "y")
            echo -n "$file" | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" & ;;
        "Y")
            echo -n "$fullpath" | xclip -selection clipboard &&
            notify-send "$fullpath copied to clipboard" & ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "e")
            gimp "$file" & ;;
    esac
done
