all: contacts.tsv userscripts/0-HOME userscripts/startnumen

contacts.tsv:
	ln -s ~/dotfiles.private/contacts.tsv

userscripts/0-HOME:
	ln -s ~/dotfiles/scripts/homecommand.sh userscripts/0-HOME

userscripts/startnumen:
	ln -s ~/dotfiles/scripts/startnumen.sh userscripts/startnumen

