#!/usr/bin/env sh

source ~/.profile

sxmo_audioout.sh Speaker
amixer sset 'Line Out Source' 'Mono Differential','Mono Differential'
amixer set "Line Out" 50%
mpv --quiet --no-video ~/dotfiles/media/cylontune_low.ogg &
feh --bg-fill -z ~/dotfiles/media/pine.jpg


if ! pgrep -f sxmo_modemmonitor.sh; then
    sleep 30 && sxmo_modemmonitortoggle.sh 2> /tmp/modemtoggle.log >&2 &
    sleep 32 && ~/dotfiles/sxmo/initsecrets.sh &
fi
~/dotfiles/homecommand.sh status &
~/dotfiles/notifyclient.sh &

