#!/usr/bin/env sh

source ~/.profile

sxmo_audioout.sh Speaker
amixer sset 'Line Out Source' 'Mono Differential','Mono Differential'
amixer set "Line Out" 50%
mpv --quiet --no-video ~/dotfiles/media/cylontune_low.ogg &
feh --bg-fill -z ~/dotfiles/media/pine.jpg

if [ -e ~/dotfiles/sxmo/initsecrets.sh ]; then
    ~/dotfiles/sxmo/initsecrets.sh
fi

if ! pgrep -f sxmo_modemmonitor.sh; then
    sleep 30 && sxmo_modemmonitortoggle.sh &
fi
~/dotfiles/homecommand.sh status &
~/dotfiles/notifyclient.sh &

