#!/bin/sh
rm ~/.mblaze/seq*
cd ~/Maildir/cur/
nr=$(ls | tail -n 250 | msort -r | mseq -S | mscan -f "%-3n %c%u%r %10d <span fgcolor=\"darkcyan\">%17f</span> ICON %2i%s" | ~/dotfiles/mblaze2pango.sh | rofi -matching glob -tokenize -i -no-sort -no-levenshtein-sort -p "Mail" -markup -markup-rows -dmenu | cut -d " " -f 1)
if [ -n "$nr" ]; then
    ATTACHDIR=~/Downloads/mailattachments
    rm -rf "$ATTACHDIR"
    mkdir -p "$ATTACHDIR"
    cd "$ATTACHDIR"
    if ls ~/Downloads/mailattachments/* > /dev/null; then
        ~/dotfiles/dmenu-files.sh "$ATTACHDIR" -t &
    fi
    mshow -x "$nr" #extract attachments
    cd -
    foot mshow -N "$nr"
fi
cd -
