#!/usr/bin/env sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
#xclip -h >/dev/null || exit

chosen=$(cut -d ';' -f1 ~/dotfiles/emoji | rofi -dmenu -font "Monospace 32" | sed "s/ .*//")


# Exit if none chosen.
[ -z "$chosen" ] && exit

echo "$chosen" | tr -d '\n' | xclip -selection clipboard

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
#if [ -n "$1" ]; then
xdotool type "$chosen"
#else
	#notify-send "'$chosen' copied to clipboard." &

