#!/usr/bin/env sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
#xclip -h >/dev/null || exit




if [ -n "$WAYLAND_DISPLAY" ]; then
    chosen=$(cut -d ';' -f1 ~/dotfiles/emoji | bemenu -p "Emoji" -n -l 30 --fn "Monospace 16" | sed "s/ .*//")
else
    chosen=$(cut -d ';' -f1 ~/dotfiles/emoji | rofi -dmenu -font "Monospace 32" | sed "s/ .*//")
fi

[ -z "$chosen" ] && exit

if [ -n "$WAYLAND_DISPLAY" ]; then
    echo "$chosen" | tr -d '\n' | wl-copy
    wtype "$chosen"
else
    echo "$chosen" | tr -d '\n' | xclip -selection clipboard
    xdotool type "$chosen"
fi



# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
#if [ -n "$1" ]; then
#else
	#notify-send "'$chosen' copied to clipboard." &

