#!/usr/bin/env sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
#xclip -h >/dev/null || exit


. ~/dotfiles/colorargs.sh

if [ -n "$WAYLAND_DISPLAY" ]; then
    chosen=$(cut -d ';' -f1 ~/dotfiles/emoji | bemenu -p "Emoji" -n -l 30 --fn "$BEMENU_FONT" $BEMENU_COLORARGS | sed "s/ .*//")
else
    chosen=$(cut -d ';' -f1 ~/dotfiles/emoji | rofi -dmenu -font "$BEMENU_FONT" | sed "s/ .*//")
fi

[ -z "$chosen" ] && exit

if [ -n "$WAYLAND_DISPLAY" ]; then
    echo "$chosen" | tr -d '\n' | wl-copy
    wtype "$chosen"
else
    echo "$chosen" | tr -d '\n' | xclip -selection clipboard
    xdotool type "$chosen"
fi
