#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in feh,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# Sci-Hub's domain occasionally changes due to shutdowns:
scihub="http://sci-hub.tw/"

if [ -z "$BROWSER" ]; then
    BROWSER=firefox
fi
if [ -z "$DISPLAY" ]; then
    BROWSER=w3m
fi
if [ -z "$TERMINAL" ]; then
    TERMINAL=urxvt
fi
if [ -z "$EDITOR" ]; then
    EDITOR=vim
fi

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

if [ -f /tmp/linkhandler.target ]; then
    TARGET=$(cat /tmp/linkhandler.target)
    play ~/dotfiles/media/glass_low.ogg > /dev/null 2>/dev/null &
else
    TARGET=0
    play ~/dotfiles/media/glass.ogg > /dev/null 2>/dev/null &
fi

if [ "$TARGET" = "0" ]; then
    case "$1" in
        *mkv|*webm|*mp4|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*|*gifv|*v.redd.it*|*gifs.com*)
            setsid mpv --ytdl-format="bestvideo[height<=1080]+bestaudio" --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 & ;;
        *png|*jpg|*jpe|*jpeg|*gif)
            case "$1" in
                http*)
                    wget "$1" -O /tmp/image
                    setsid sxiv -a /tmp/image >/dev/null 2>&1 & ;;
                *)
                    setsid sxiv -a "$1" >/dev/null 2>&1 & ;;
            esac
            ;;
        *mp3|*flac|*opus|*mp3?source*)
            setsid mpv curl -LO "$1" >/dev/null 2>&1 & ;;
        *springer.com*)
            setsid curl -sO "$(curl -s "$scihub$*" | grep -Po "(?<=location.href=').+.pdf")" >/dev/null 2>&1 & ;;
        *)
            if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
            else setsid "$BROWSER" "$1" >/dev/null 2>&1 & fi ;;
    esac
else
    case "$1" in
        *mkv|*webm|*mp4|*mp3|*flac|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*|*gifv|*v.redd.it*|*gifs.com*)
           ~/dotfiles/notifysend.sh "home/command/videoplayer/pi$TARGET" "$1"
           ~/dotfiles/notifysend.sh "home/command/video/pi$TARGET/play" "$1"
           ;;
        *png|*jpg|*JPG|*jpeg|*gif)
           ~/dotfiles/notifysend.sh "home/command/videoplayer/pi$TARGET" "$1"
           ~/dotfiles/notifysend.sh "home/command/video/pi$TARGET/play" "$1"
           ;;
        *)
           play ~/dotfiles/media/error.wav > /dev/null 2>/dev/null &
           ;;
    esac
fi
