all: directories \
	 aerc alacritty dunst foot hypr lf mako mimeapps.list ncmpcpp.config newsboat nvim openbox ranger rofi sxiv tuir tut user-dirs.dirs waybar zathura

aerc alacritty dunst foot hypr lf mako mimeapps.list ncmpcpp.config newsboat nvim openbox ranger rofi sxiv tuir tut user-dirs.dirs waybar zathura:
	ln -s ~/dotfiles/$@

directories:
	~/dotfiles/scripts/cache-dirs.sh

update:
	~/dotfiles/scripts/cache-dirs.sh
