all: directories \
	 aerc alacritty dunst foot hypr lf mako mimeapps.list ncmpcpp.config newsraft nvim openbox ranger rofi sxiv tuir tut user-dirs.dirs waybar zathura senpai mpv gh-dash iamb yazi starship.toml kanshi river ytfzf kdeglobals rmpc

aerc alacritty dunst foot hypr lf mako mimeapps.list ncmpcpp.config newsraft nvim openbox ranger rofi sxiv tuir tut user-dirs.dirs waybar zathura senpai mpv gh-dash iamb yazi starship.toml kanshi river ytfzf kdeglobals rmpc:
	ln -sf ~/dotfiles/$@ $@

directories:
	~/dotfiles/scripts/cache-dirs.sh || true

update:
	~/dotfiles/scripts/cache-dirs.sh || true
