#!/bin/sh

# Show date and time in other time zones

search=$1
format='%a %F %T'

timedatectl list-timezones \
| grep -i "$search"        \
| while read z
  do
      d=$(TZ=$z date +"$format")
      printf "%-34s %23s\n" "$z" "$d"
  done
