#!/usr/bin/env sh

pkill -CONT conky

if [ "$1" != "rtc" ]; then
    #only run when not woken up by rtc

    echo "[$(date)] Postwake hook (reason=$1)" >&2


    #kill the one already running (if any)
    killall notifyhandler.sh notifyclient.sh mosquitto_sub

    if ! nmcli dev show | grep -q "(connected)"; then
        nmcli con up ifname wlan0 || nmcli con up ifname cdc-wdm0
    fi

    #wait for connection (max 15s) and restart notification handler in background
    (
        (ping -c 1 -W 15 anaproy.nl >/dev/null 2>/dev/null && MQTT_SILENT_END=1 ~/dotfiles/notifyclient.sh) || mpv --no-video --really-quiet ~/dotfiles/media/error.wav
    ) &

fi
