#!/bin/sh

pkill -CONT conky
sxmo_statusbarupdate.sh

if [ "$1" != "rtc" ]; then
    #only run when not woken up by rtc

    echo "[$(date)] Postwake hook (reason=$1)" >&2


    #kill the one already running (if any)
    if pidof mosquitto_sub > /dev/null; then
        touch /tmp/.notifyclient.silent
        killall mosquitto_sub notifyhandler.sh notifyclient.sh #kill the one already running
        rm /tmp/.notifyclient.silent
    fi

    NMSTATE=$(nmcli -c no -t -f DEVICE,STATE con show)
    if ! echo "$NMSTATE" | grep -q "wlan0:activated"; then
        nmcli con up ifname wlan0
    fi
    if ! echo "$NMSTATE" | grep -q "cdc-wdm0:activated"; then
        nmcli con up ifname cdc-wdm0
    fi

    #wait for connection (max 15s) and restart notification handler in background
    (
        (ping -c 1 -W 15 anaproy.nl >/dev/null 2>/dev/null && ~/dotfiles/notifyclient.sh)
    ) &

fi
