#!/usr/bin/env sh

date >> /tmp/rtc

if pidof mosquitto_sub; then
       sleep 4
else
       NMSTATE=$(nmcli -c no -t -f DEVICE,STATE con show)
       if ! echo "$NMSTATE" | grep -q "wlan0:activated"; then
           nmcli con up ifname wlan0
       fi
       if ! echo "$NMSTATE" | grep -q "cdc-wdm0:activated"; then
           nmcli con up ifname cdc-wdm0
       fi
       #wait for connection (max 15 s) and process three seconds of notifications before disconnecting
       ping -c 1 -W 15 anaproy.nl >/dev/null 2>/dev/null && \
       MQTT_SILENT_START=1 MQTT_SILENT_END=1 MQTT_OPTIONS="-W 3" ~/dotfiles/notifyclient.sh
fi
