#!/bin/sh

# This script is executed after you received a text
#You can use it to play a notification sound or forward the sms elsewhere

#The following parameters are provided:
#$1 = Contact Name or Number (if number not in contacts)
#$2 = Text

~/dotfiles/notifysend.sh notify/proycon/sms "$@" &

mpv --quiet --no-video /usr/share/sxmo/notify.ogg
