#!/usr/bin/env sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

source ~/.profile

echo "$DBUS_SESSION_BUS_ADDRESS" > "$CACHEDIR"/dbus.bus

sxmo_audioout.sh Speaker
amixer sset 'Line Out Source' 'Mono Differential','Mono Differential'
amixer set "Line Out" 50%

sxmo_lock_idle.sh &

if ! pgrep -f sxmo_modemmonitor.sh; then
    sleep 20 && sxmo_modemmonitortoggle.sh 2> /tmp/modemtoggle.log >&2 &
    sleep 22 && ~/dotfiles/sxmo/initsecrets.sh &
fi

~/dotfiles/homecommand.sh status &
~/dotfiles/notifyclient.sh &

if [ -n "$WAYLAND_DISPLAY" ]; then
    pgrep -f homestatus_widget.sh || ~/dotfiles/sxmo/homestatus_widget.sh
fi
