#!/usr/bin/env sh

pkill -CONT conky

pidof mosquitto_sub || sxmo_hooks.sh postwake

#request status update from home automation
~/dotfiles/notifysend.sh "/home/command/status" "ON"

#force a conky update (assuming we got the response)
sleep 2 && pkill -USR2 conky
