#!/bin/sh

# This hook is called when the system becomes unlocked again

# Start a periodic daemon (10s) "try to go to lock" after 120 seconds
# Resume tasks stop daemons
sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
	timeout 120 'sxmo_daemons.sh start periodic_deeper sxmo_run_periodically.sh 10 sxmo_screenlock_deeper.sh --idle' \
	resume 'sxmo_daemons.sh stop periodic_deeper'

#request status update from home automation
~/dotfiles/notifysend.sh "home/command/status" "ON"

