#!/bin/sh
bspc config top_padding 18
bspc config border_width 2
bspc config split_ratio 0.52
bspc config -d ^1 window_gap 50
bspc config -d ^4 window_gap 25
bspc config -d ^6 window_gap 25
bspc config -d ^12 window_gap 50
bspc config window_gap 5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc monitor -d im edit www mail term irc 7 8 9 10 11 12 
bspc rule -a Gimp desktop=^8 follow=on 
bspc rule -a Firefox desktop=^3
bspc rule -a gajim desktop=^1
bspc rule -a mplayer floating=on

