#!/bin/sh
# aerc filter which runs w3m using unshare  to prevent
# any phoning home by rendered emails
exec unshare -n -r w3m \
	-T text/html \
	-cols $(tput cols) \
	-dump \
	-o display_image=false \
	-o display_link_number=true
