#!/bin/sh

mod="Mod4"
alt="Mod1"
term="foot"
menu="bemenu"
menurun="bemenu-run"

riverctl map normal $mod+Shift Return spawn 'foot'

riverctl map normal $mod+Shift Q close


# view focus
riverctl map normal $mod Return zoom
riverctl map normal $mod N focus-view next
riverctl map normal $mod E focus-view previous

# main factor/count
riverctl map normal $mod H send-layout-cmd rivercarro 'main-ratio -0.05'
riverctl map normal $mod L send-layout-cmd rivercarro 'main-ratio +0.05'
riverctl map normal $mod+Shift H send-layout-cmd rivercarro 'main-count +1'
riverctl map normal $mod+Shift L send-layout-cmd rivercarro 'main-count -1'

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left"
# And for monocle
riverctl map normal $mod M     send-layout-cmd rivercarro "main-location monocle"

# move/resize
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# toggle float/fullscreen
riverctl map normal $mod Space spawn $menurun -l 20
riverctl map normal $mod Space toggle-float
riverctl map normal $mod+Shift F toggle-fullscreen

# multi-output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# screenshots
riverctl map normal $mod F3 spawn /home/proycon/dotfiles/homecommand.sh
riverctl map normal $alt F3 spawn /home/proycon/dotfiles/homecommand.sh mute
riverctl map normal $alt F5 spawn /home/proycon/dotfiles/emojiselect
riverctl map normal $mod F4 spawn 'grim -g "$(slurp)" "/home/proycon/$(date +%Y-%m-%d-%H%M%S)_screenshot.png" && notify-send "Screenshot ready"'
riverctl map normal $mod F5 spawn /home/proycon/dotfiles/opensxiv.sh
riverctl map normal $mod F6 spawn $term --title newsboat newsboat
riverctl map normal $mod F7 spawn $term --title ncmpcpp ncmpcpp
riverctl map normal $mod F8 spawn $term --title youtube ytfzt -t
riverctl map normal $mod F10 spawn pamixer -t && play /home/proycon/dotfiles/media/key.wav
riverctl map normal $mod F11 spawn pamixer --allow-boost -d 5 && play /home/proycon/dotfiles/media/key.wav
riverctl map normal $mod F12 spawn pamixer --allow-boost -i 5 && play /home/proycon/dotfiles/media/key.wav
riverctl map normal $mod slash spawn /home/proycon/dotfiles/timetracker.sh
riverctl map normal $mod+Shift slash spawn /home/proycon/dotfiles/timetracker.sh 15
riverctl map normal $mod+Ctrl+Shift slash spawn /home/proycon/dotfiles/timetracker.sh 60
riverctl map normal $mod+Shift W spawn /home/proycon/dotfiles/buku-dmenu
riverctl map normal $mod U spawn /home/proycon/dotfiles/dmenu-files.sh /nettmp -t
riverctl map normal $mod O spawn /home/proycon/dotfiles/dmenu-files.sh /home/proycon -t
riverctl map normal $mod N spawn /home/proycon/dotfiles/network-menu.sh

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done
tags1to9=$(((1 << 9) - 1))
riverctl map normal $mod 0 set-focused-tags $tags1to9
riverctl map normal $mod+Shift 0 set-view-tags $tags1to9

# passthrough mode for nested sessions
riverctl declare-mode passthrough
riverctl map normal $mod Semicolon enter-mode passthrough
riverctl map passthrough $mod Semicolon enter-mode normal

riverctl set-repeat 50 300

riverctl xcursor-theme Adwaita

# float stuff with app-id "float"
riverctl float-filter-add app-id float
riverctl float-filter-add app-id menu
riverctl float-filter-add app-id mpv
riverctl float-filter-add app-id scratchpad

riverctl spawn rivercarro
riverctl default-layout rivercarro

swaybg /home/proycon/dotfiles/media/green-leafed-closeup.jpg fit &
swaybar &
mako &
amixer sset Master unmute
pulseaudio --start
killall mosquitto_sub
/home/proycon/dotfiles/notifyclient.sh &
/home/proycon/dotfiles/media/cylontune_low.ogg &
nm-applet &
$term --title scratchpad /home/proycon/bin/tm scratchpad &
udiskie &
