#!/bin/sh
# configversion: 3b2e8ccba705f6788a2d062394706bd2
# ^-- for SXMO compatibility

echo "River init">&2

if [ "$SXMO_WM" = "river" ]; then
    #SXMO is not launced via startriver.sh, we still need to import the environment
    . ~/.config/river/env.sh
fi

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    echo "No dbus session!">&2
fi

killall client.sh
pkill -f lighthome
rm /tmp/locked

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

if [ -e ~/dotfiles/kanshi/$HOSTNAME.config ]; then
    kanshi -c ~/dotfiles/kanshi/$HOSTNAME.config &
fi

if [ ! -e /run/systemd/system ]; then
    #we do not use systemd

    #kill previous session, if any
    killall wireplumber pipewire-pulse pipewire

    if ! pgrep -x pipewire; then
        #/etc/pulse/client.conf: autospawn = no
        riverctl spawn pipewire 
    fi
    if ! pgrep -x pipewire-pulse; then
        riverctl spawn pipewire-pulse
    fi
    if ! pgrep -x wireplumber; then
        riverctl spawn wireplumber
    fi
fi

# bigger brighter cursors and suitable for dark themes, because I keep losing them
riverctl xcursor-theme Breeze_Light 48
gsettings set org.gnome.desktop.interface cursor-theme Breeze_Light
gsettings set org.gnome.desktop.interface cursor-size 48

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
if [ -n "$OVERRIDESHELL" ]; then
    riverctl map normal Super+Shift Return spawn "foot -e $OVERRIDESHELL"
else
    riverctl map normal Super+Shift Return spawn foot
fi

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift Backspace exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super Up    focus-view up
riverctl map normal Super Right focus-view next
riverctl map normal Super Down  focus-view down
riverctl map normal Super Left  focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Z focus-output next
#riverctl map normal Super Comma focus-output previous

riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super+Shift Tab focus-output next

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivercarro
riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivercarro
riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1"

# Mod+{Up,Right,Down,Left} to change layout orientation
# And for monocle
riverctl map normal Super M     send-layout-cmd rivercarro "main-location-cycle monocle,left"
riverctl map normal Super V     send-layout-cmd rivercarro "main-location-cycle monocle,left"
# Cycle through layout
riverctl map normal Super comma     send-layout-cmd rivercarro "main-location left"
riverctl map normal Super period     send-layout-cmd rivercarro "main-location top"

# Add others rivercarro's commands the same way with the keybinds you'd like.
# e.g.
riverctl map normal Super Minus send-layout-cmd rivercarro "inner-gaps -5"
riverctl map normal Super Equal send-layout-cmd rivercarro "inner-gaps +5"
riverctl map normal Super+Shift Minus send-layout-cmd rivercarro "outer-gaps -5"
riverctl map normal Super+Shift Equal send-layout-cmd rivercarro "outer-gaps +5"
# riverctl map normal Super <keys> send-layout-cmd rivercarro "outer-gaps -1"
# riverctl map normal Super <keys> send-layout-cmd rivercarro "outer-gaps +1"
# riverctl map normal Super <keys> send-layout-cmd rivercarro "width-ratio -0.1"
# riverctl map normal Super <keys> send-layout-cmd rivercarro "width-ratio +0.1"


# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Shift H resize horizontal -100
riverctl map normal Super+Shift J resize vertical 100
riverctl map normal Super+Shift K resize vertical -100
riverctl map normal Super+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

scratch_tag=$((1 << 20 ))

for i in $(seq 1 9)
do
    tags=$(( (1 << (i - 1)) ))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

#riverctl map normal Super s set-view-tags ${sticky_tag}		# set sticky

# Set spawn tagmask to ensure new windows do not have the scratchpad tag unless explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

riverctl map normal Super 0 set-focused-tags $all_but_scratch_tag

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
#riverctl map normal Super 0 set-focused-tags $all_tags
#riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super F toggle-float
riverctl map normal Super+Shift F toggle-fullscreen

riverctl map normal Super+Control Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super+Control Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super+Control Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super+Control Left  send-layout-cmd rivercarro "main-location left"

#custom actions
if command -v kickoff; then
    riverctl map normal Super Space spawn 'kickoff'
else
    riverctl map normal Super Space spawn 'bemenu-run --fn "Monospace 22" -l 20'
fi
if command -v fuzzel; then
    riverctl map normal Super+Shift space spawn 'fuzzel'
else
    riverctl map normal Super+Shift space spawn 'rofi -sidebar-mode -show drun'
fi
if [ -n "$OVERRIDESHELL" ]; then
    riverctl map normal Super F1 spawn "foot --title aerc $OVERRIDESHELL -e aerc"
else
    riverctl map normal Super F1 spawn 'foot --title aerc aerc'
fi
riverctl map normal Super E spawn ~/dotfiles/scripts/translate.sh
riverctl map normal Alt F2 spawn ~/bin/lala
riverctl map normal Alt+Shift, F2 spawn 'killall snapclient'
riverctl map normal Super F2 spawn "foot --title nvim ~/bin/tm nvim"
riverctl map normal Super F3 spawn ~/dotfiles/scripts/homecommand.sh
riverctl map normal Super F4 spawn ~/dotfiles/scripts/screenshot.sh
riverctl map normal Super+Shift F4 spawn "~/dotfiles/scripts/screenshot.sh region"
riverctl map normal Super+Control+Shift F4 spawn "~/dotfiles/scripts/screenshot.sh annotate"
if [ "$HOSTNAME" = "pollux" ]; then
    riverctl map normal Alt F3 spawn "~/dotfiles/scripts/homecommand.sh lights/office/on"
else
    riverctl map normal Alt F3 spawn "~/dotfiles/scripts/homecommand.sh mute"
fi
riverctl map normal Super F5 spawn ~/dotfiles/scripts/emojiselect
riverctl map normal Alt F5 spawn ~/dotfiles/scripts/emojiselect
#riverctl map normal Super F6 spawn "foot --title newsraft newsraft"
#riverctl map normal Super+Shift F6 spawn "foot --title ncmpcpp ncmpcpp"
#riverctl map normal Super F7 spawn "~/dotfiles/scripts/startchat.sh"
#riverctl map normal Super F8 spawn "foot --title ytfzt ytfzt -t"
riverctl map normal Super+Alt slash spawn "todo.sh rofi listall @work"
riverctl map normal Super+Shift slash spawn "todo.sh timetrack stop"
riverctl map normal Super+Control slash spawn "foot -e todo.sh edit"
riverctl map normal Super slash spawn "todo.sh rofi list @work"
riverctl map normal Super backslash spawn "todo.sh rofi list -@work"
riverctl map normal Super+Alt backslash spawn "todo.sh rofi listall -@work"
riverctl map normal Super+Shift backslash spawn "todo.sh timetrack stop"
riverctl map normal Super+Control backslash spawn "foot -e todo.sh edit"
riverctl map normal Super dead_acute spawn "todo.sh rofi list @calendar"
riverctl map normal Super apostrophe spawn "todo.sh rofi list @calendar"
riverctl map normal Super dead_tilde spawn newmail
riverctl map normal Super dead_grave spawn curmail
riverctl map normal Super w spawn ~/dotfiles/scripts/buku-dmenu
riverctl map normal Super u spawn "~/dotfiles/scripts/dmenu-files.sh /nettmp -t"
riverctl map normal Super+Shift u spawn "~/dotfiles/scripts/dmenu-files.sh /home/proycon/Downloads -t"
riverctl map normal Super i spawn "~/dotfiles/scripts/dmenu-files.sh /home/proycon -t"
riverctl map normal Super o spawn ~/dotfiles/scripts/castnone.sh
riverctl map normal Super+Shift o spawn ~/dotfiles/scripts/castpi1.sh
riverctl map normal Super+Control o spawn ~/dotfiles/scripts/castpi2.sh 
riverctl map normal Super p spawn ~/dotfiles/scripts/passmenu.sh
riverctl map normal Super y spawn "foot -e ytfzf --async-thumbnails --preview-side=right -t -T mpv -u ~/dotfiles/scripts/linkhandler --loop --rii"
riverctl map normal Super+Shift p spawn ~/dotfiles/scripts/otpmenu.sh
riverctl map normal Super n spawn ~/dotfiles/scripts/network-menu.sh
riverctl map normal Super+Shift n spawn ~/dotfiles/scripts/startnumen.sh
riverctl map normal Super+Control k spawn ~/dotfiles/scripts/killmenu.sh
riverctl map normal Super b spawn ~/dotfiles/scripts/switchbg.sh
riverctl map normal Super escape spawn "~/dotfiles/scripts/lock.sh force"
riverctl map normal Control escape spawn "~/dotfiles/scripts/lock.sh force"
riverctl map normal Super+Shift escape spawn ~/dotfiles/scripts/suspend.sh
riverctl map normal Control+Shift escape spawn ~/dotfiles/scripts/suspend.sh
riverctl map normal Super+Shift g spawn "wlopm --toggle \*"
riverctl map normal Super+Shift z spawn "wlopm --toggle DP-2"

riverctl map normal Super F9 spawn "riverctl keyboard-layout $KB_OPTS proybasic && play ~/dotfiles/media/key.wav"
riverctl map normal Alt F9 spawn "riverctl keyboard-layout $KB_OPTS proylatin && play ~/dotfiles/media/key.wav"
riverctl map normal Alt F10 spawn "riverctl keyboard-layout $KB_OPTS proyeo && play ~/dotfiles/media/key.wav"
riverctl map normal Alt+Shift F10 spawn "riverctl keyboard-layout $KB_OPTS proyipa && play ~/dotfiles/media/key.wav"
riverctl map normal Alt F11 spawn "riverctl keyboard-layout $KB_OPTS proyru && play ~/dotfiles/media/key.wav"
riverctl map normal Alt F12 spawn "riverctl keyboard-layout $KB_OPTS proyar && play ~/dotfiles/media/key.wav"

riverctl map normal Super F10  spawn 'pamixer --toggle-mute && aplay ~/dotfiles/media/submit.wav'
riverctl map normal Super F11  spawn 'pamixer -d 5 && aplay ~/dotfiles/media/submit.wav'
riverctl map normal Super F12  spawn 'pamixer -i 5 && aplay ~/dotfiles/media/submit.wav'

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x1affff
riverctl border-color-unfocused 0x595959

# Set keyboard repeat rate
riverctl set-repeat 50 300

#use lswt to find app IDs and titles 
riverctl rule-add -app-id 'float*' float
riverctl rule-add -app-id 'popup*' float
riverctl rule-add -title 'Select file*' float
riverctl rule-add -title 'Open file*' float
riverctl rule-add -title 'Save file*' float
riverctl rule-add -title '*dialog*' float
riverctl rule-add -title 'Confirm*' float

# Use server-side decorations everywhere 
riverctl rule-add -app-id '*' ssd
#riverctl rule-add -app-id "org.telegram.desktop" ssd
#riverctl rule-add -app-id 'libreoffice*' ssd
#riverctl rule-add -app-id 'org.pwmt.zathura' ssd
#riverctl rule-add -app-id 'imv' ssd
#riverctl rule-add -app-id 'gimp' ssd


gsettings set org.gnome.desktop.interface text-scaling-factor 1.8
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

if [ "$SXMO_WM" = "river" ]; then
    #SXMO compatibility
    echo "Configuring sxmo compatibility...">&2

    riverctl map normal None XF86AudioRaiseVolume  spawn 'sxmo_audio.sh vol up'
    riverctl map normal None XF86AudioLowerVolume  spawn 'sxmo_audio.sh vol down'
    riverctl map normal None XF86AudioMute         spawn 'sxmo_audio.sh vol togglemute'
    riverctl map normal None XF86AudioMicMute      spawn 'sxmo_audio.sh mic togglemute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map normal None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map normal None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map normal None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map normal None XF86AudioNext  spawn 'playerctl next'

    # Control backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map normal None XF86MonBrightnessUp   spawn 'sxmo_brightness.sh up'
    riverctl map normal None XF86MonBrightnessDown spawn 'sxmo_brightness.sh down'

    # Launch appmenu
    riverctl map normal Super A spawn 'sxmo_appmenu.sh'
    riverctl map normal Super+Shift A spawn 'sxmo_appmenu.sh sys'

    # Start your launcher
    riverctl map normal Super D spawn 'bemenu-run'

    # Manual locker
    riverctl map normal Super G spawn 'sxmo_state.sh set locker'

    # Shutdown
    riverctl map normal Super T spawn 'sxmo_appmenu.sh power'

    for mode in normal locked; do
        riverctl map-switch $mode lid open spawn 'sxmo_wm.sh display on'
        riverctl map-switch $mode lid close spawn 'sxmo_wm.sh display off'
    done

    if [ "$HOSTNAME" != "toren" ]; then
        # sxmo on phones rather than laptop

        # bonsaictl should be working, but for an obscure reason it doesn't.
        multikey_retrocompat() {
            sxmo_multikey.sh clear
            for mode in normal locked
            do
                riverctl map $mode None XF86PowerOff spawn "sxmo_multikey.sh \
                    powerbutton \
                    powerbutton_one \
                    powerbutton_two \
                    powerbutton_three"
                riverctl map $mode None XF86AudioRaiseVolume spawn \
                    "sxmo_multikey.sh \
                    volup \
                    volup_one \
                    volup_two \
                    volup_three"
                riverctl map $mode None XF86AudioLowerVolume spawn \
                    "sxmo_multikey.sh \
                    voldown \
                    voldown_one \
                    voldown_two \
                    voldown_three"
            done
        }

        multikey_retrocompat
    fi
fi

riverctl keyboard-layout $KB_OPTS proybasic
# Set the default layout generator to be rivercarro and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
riverctl default-attach-mode bottom
riverctl set-cursor-warp on-focus-change
riverctl focus-follows-cursor always
rivercarro -outer-gaps 0 -inner-gaps 5 -per-tag &
riverctl spawn ~/dotfiles/scripts/switchbg.sh
riverctl spawn "waybar"
if [ -z "$SXMO_WM" ]; then
    #not on sxmo (sxmo spawns it for us)
    riverctl spawn "dunst" 
fi
riverctl spawn "udiskie"
riverctl spawn "setsid /home/proycon/projects/lighthome/client.sh"
if [ "$HOSTNAME" = "toren" ]; then
    riverctl spawn "swayidle timeout 500 '/home/proycon/dotfiles/scripts/lock.sh' timeout 600 '/home/proycon/dotfiles/scripts/trysuspend.sh'"
else
    riverctl spawn "swayidle timeout 600 '/home/proycon/dotfiles/scripts/lock.sh' timeout 900 'wlopm --off \*' resume 'wlopm --on \*' timeout 3600 '/home/proycon/dotfiles/scripts/trysuspend.sh'"
fi

#swayidle -w timeout 300 'swaylock -f -i $wallpaper' timeout 600 'wlopm --off \*;swaylock -F -i $wallpaper' resume 'wlopm --on \*' \ before-sleep 'swaylock -f -i $wallpaper' &

#tells dbus about the graphical session (required for various things like password prompt to work)
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

if [ ! -e /run/systemd/system ]; then
    #start portals if not on systemd
    if [ -e /usr/lib/xdg-desktop-portal-wlr ]; then
        pkill -f /usr/lib/xdg-desktop-portal-wlr
        riverctl spawn "/usr/lib/xdg-desktop-portal-wlr"
    elif [ -e /usr/libexec/xdg-desktop-portal-wlr ]; then
        pkill -f /usr/libexec/xdg-desktop-portal-wlr
        riverctl spawn "/usr/libexec/xdg-desktop-portal-wlr"
    else
        echo "No XDG portal found">&2
    fi
fi

if [ "$HOSTNAME" = "pollux" ]; then
    #left monitor uses top layout
    riverctl focus-output DP-1 && riverctl send-layout-cmd rivercarro "main-location top"
    #right monitor is default
    riverctl focus-output DP-2
    riverctl set-focused-tags 1

    #set default sources for sound
    #view sources with: pactl list short sources
    pactl set-default-sink alsa_output.pci-0000_17_00.6.3.analog-stereo.monitor
    pactl set-default-source alsa_input.usb-Samson_Technologies_Samson_C01U_Pro_Mic-00.3.analog-stereo 
fi

fcitx5 &

#apparmor notifications
#riverctl spawn "aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log"

# Auto-start all applications on the right tag 
if [ "$HOSTNAME" = "pollux" ]; then
    riverctl rule-add -app-id 'foot'-title "nvim*" output DP-2
    riverctl rule-add -app-id 'foot' -title 'aerc*' output DP-1
    riverctl rule-add -app-id 'firefox' output DP-1
    riverctl rule-add -app-id 'firefox-esr' output DP-1
    riverctl rule-add -app-id 'librewolf' output DP-1
    riverctl rule-add -app-id 'foot' -title 'local*' output DP-1
    riverctl rule-add -app-id 'org.telegram.desktop' output DP-1
    riverctl rule-add -app-id 'org.gnome.Fractal' output DP-1
    riverctl rule-add -app-id 'nheko' output DP-1
    riverctl rule-add -app-id 'senpai' output DP-1
    riverctl rule-add -app-id 'dev.geopjr.Tuba' output DP-1
    riverctl rule-add -app-id 'im.dino.Dino' output DP-1
    riverctl rule-add -app-id 'foot' -title 'newsraft' output DP-1
    riverctl rule-add -app-id 'foot' -title 'remote*' output DP-1
fi
riverctl rule-add -app-id 'foot' -title "nvim*" tags 2 #workspace 2 
riverctl rule-add -app-id 'foot' -title 'aerc*' tags 1 #workspace 1
riverctl rule-add -app-id 'firefox' tags 4 #workspace 3 = 0b100 = 4
riverctl rule-add -app-id 'firefox-esr' tags 4 #workspace 3 = 0b100 = 4
riverctl rule-add -app-id 'librewolf' tags 4 #workspace 3 = 0b100 = 4
riverctl rule-add -app-id 'foot' -title 'local*' tags 8 #workspace 4
riverctl rule-add -app-id 'org.telegram.desktop' tags 64 #workspace 7 = 0b1000000 = 64
riverctl rule-add -app-id 'nheko' tags 64 #workspace 7 = 0b1000000 = 64
riverctl rule-add -app-id 'im.dino.Dino' tags 64 #workspace 7
riverctl rule-add -app-id 'senpai' tags 64 #workspace 7 = 0b1000000 = 64
riverctl rule-add -app-id 'foot' -title '*senpai*' tags 64 #workspace 7 = 0b1000000 = 64
riverctl rule-add -app-id 'dev.geopjr.Tuba' tags 32 #workspace 6 = 0b100000 = 32
riverctl rule-add -app-id 'foot' -title 'newsraft' tags 32 #workspace 6 = 0b100000 = 32
riverctl rule-add -app-id 'foot' -title 'remote*' tags 128 #workspace 8

if [ -z "$SXMO_WM" ] || [ "$HOSTNAME" = "toren" ]; then
    #not sxmo or sxmo on toren

    #ensure we hacve network
    if nmcli -t 2> /dev/null; then
        #network manager is running
        while ! nmcli connection show --active | grep -E "(wifi|ethernet)"; do
            #wait for network connection
            sleep 2
        done
        while [ "$(date +%Y)" -lt 2024 ]; do
            #wait for NTP time to sync (otherwise all network stuff can't connect because of invalid certificates)
            sleep 1
        done
    fi


    #prompt for master password

    #use --login if passwordless login is enabled, otherwise use --start
    PASS=""
    while [ -z "$PASS" ]; do
        echo "waiting for password for $HOSTNAME">&2
        PASS=$(pass "$HOSTNAME") #blocks until password is given
    done
    ps aux | grep gnome-keyring-daemon | grep -v grep
    if ! pidof gnome-keyring-daemon || [ "$HOSTNAME" = "toren" ]; then
        echo "starting new gnome-keyring-daemon">&2
        echo -n "$PASS" | gnome-keyring-daemon --daemonize --login --components=pkcs11,secrets,ssh,gpg
    fi
    echo "initialising gnome-keyring-daemon (--start)">&2
    gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg
    unset PASS #very important!
    ps aux | grep gnome-keyring-daemon | grep -v grep


    #autostart stuff
    if [ -n "$OVERRIDESHELL" ]; then
        #with nushell overriding default shell
        riverctl spawn "foot --title aerc $OVERRIDESHELL -e aerc"
        riverctl spawn "foot --title newsraft $OVERRIDESHELL -e newsraft"
        riverctl spawn "foot --title senpai $OVERRIDESHELL -e senpai"
        riverctl spawn "foot --title remote $OVERRIDESHELL"
        riverctl spawn "foot --title nvim $OVERRIDESHELL -e ~/bin/tm nvim"
        riverctl spawn "foot --title local $OVERRIDESHELL -e ~/bin/tm local"
    else
        #with system default shell (zsh/bash/ash)
        riverctl spawn "foot --title remote"
        riverctl spawn "foot --title aerc aerc"
        riverctl spawn "foot --title newsraft newsraft"
        riverctl spawn "foot --title senpai senpai"
        riverctl spawn "foot --title nvim ~/bin/tm nvim"
        riverctl spawn "foot --title local ~/bin/tm local"
    fi
    riverctl spawn "firefox"
    riverctl spawn "nheko"
    riverctl spawn "tuba"
    riverctl spawn "dino"
fi

mpv --quiet ~/dotfiles/media/lovelyboot.ogg
echo "River init done">&2

[ "$SXMO_WM" = "river" ] && exec sxmo_hook_start.sh
