#!/bin/sh
# @author nate zhou  (minor adaptations by proycon)
# @since 2024,2025
# @license GNU GPL-3.0
# A calendar via XDG notification with today's date highlighted in Pango

color0="#111111"
color6="#8ec07c"

date_today=$(date +%-d)
msg_summary=$(date '+%Y-%m-%d %A')

# 1. `sed -E "s,old,new,"`
# 2. `(^|\s)` and `(\s|$)` specify the string either be surrounded with spaces or
#    the string is at the head/end of the line
# 3. `\1` and `\3` retain the 1st and 3rd match, avoid adding/removing spaces
msg_body=$(cal | tail -7 \
    | sed -E "s,(^|\s)($date_today)(\s|$),\1<span foreground=\"$color0\" background=\"$color6\"><b>$date_today</b></span>\3,")

notify-send -u low -r 3301 -t 12000 "$msg_summary" "$msg_body"
