#!/bin/sh

# Shows git log in fzf

#relies on a proper pager being set for diffs in ~/.gitconfig
ARGS=$1
while ; do
    COMMIT="$(git log --color=always --pretty="%Cgreen%cs%Creset %h %Cblue%an%Creset %Cred%d%Creset %s" $ARGS | fzf --ansi | cut -d" " -f 2)"
    if [ $? -ne 0 ] || [ -z "$COMMIT" ]; then
        break
    fi
    git show "$COMMIT" || break
done
