#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in feh,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

. /etc/os-release

# Sci-Hub's domain occasionally changes due to shutdowns:
scihub="http://sci-hub.tw/"

if [ -z "$BROWSER" ]; then
    BROWSER=firefox
fi
if [ -z "$DISPLAY" ]; then
    BROWSER=w3m
fi
if [ -z "$TERMINAL" ]; then
    if [ -n "$WAYLAND_DISPLAY" ]; then
        TERMINAL=foot
    else
        TERMINAL=urxvt
    fi
fi
if [ -z "$EDITOR" ]; then
    EDITOR=vim
fi

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

if [ -f /tmp/linkhandler.target ]; then
    TARGET=$(cat /tmp/linkhandler.target)
    paplay ~/dotfiles/media/glass_low.ogg > /dev/null 2>/dev/null &
elif [ -n "$2" ]; then
    TARGET="$2"
    paplay ~/dotfiles/media/glass_low.ogg > /dev/null 2>/dev/null &
else
    TARGET=local
    paplay ~/dotfiles/media/glass.ogg > /dev/null 2>/dev/null &
fi


case "$TARGET" in 
    local)
        case "$1" in
            http*png|http*jpg|http*jpe|http*jpeg|http*gif|http*webp|http*pdf)
                TARGET=download
                ;;
        esac
        ;;
esac

case "$TARGET" in 
    local)
        case "$1" in
            *mkv|*webm|*mp4|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*|*gifv|*v.redd.it*|*gifs.com*|*mkv?*|*mp4?*|*gifv?*)
                #handles both local and remote
                setsid mpv --vo=gpu --ytdl-format="bestvideo[height<=1080]+bestaudio" --input-ipc-server="/tmp/mpvsoc$(date +%s)" -quiet "$1" >/dev/null 2>&1 & ;;
            *png|*jpg|*jpe|*jpeg|*gif|*webp)
                setsid imv "$1" >/dev/null 2>&1 &
                ;;
            *mp3|*flac|*opus|*mp3?*|*flac?*|*opus?*|*wav)
                #handles both local and remote
                setsid mpv --profile=pseudo-gui --input-ipc-server="/tmp/mpvsoc$(date +%s)" "$1" >/dev/null 2>&1 & ;;
            *pdf)
                if [ "$NAME" = "postmarketOS" ]; then
                    setsid okular "$1" &
                else
                    setsid zathura "$1" &
                fi
                ;;
            *.md)
                if command -v mdless; then
                    if tty -s; then
                        mdless "$1"
                    else
                        setsid $TERMINAL mdless "$1"
                    fi
                elif tty -s; then
                    bat "$1"
                else
                    setsid $TERMINAL bat --style=plain --paging=always "$1"
                fi
                ;;
            *csv)
                if tty -s; then
                    tw "$1"
                else
                    setsid $TERMINAL tw "$1"
                fi
                ;;
            *tsv)
                if tty -s; then
                    tw -d"	" "$1"
                else
                    setsid $TERMINAL tw -d"	" "$1"
                fi
                ;;
            *docx|*ppt|*pptx|*xls|*xlsx|*odt|*ods|*odp)
                setsid libreoffice "$1" & ;;
            *html|http*)
                $BROWSER "$1" & ;;
            *.py|*.cpp|*.c|*.java|*.rs|*.pl|*.sh|*.tex|*.h|*.cxx|*.hxx|*.go|*.zig|*.yml|*.yaml|*.json|*.toml|*.ini|*.conf)
                if tty -s; then
                    if [ -d "$(realpath "$1")" ]; then
                        yazi "$1"
                    else
                        bat "$1"
                    fi
                else
                    if [ -d "$(realpath "$1")" ]; then
                        setsid $TERMINAL yazi "$1"
                    else
                        bat "$1"
                    fi
                fi
                ;;
            *)
                if tty -s; then
                    if [ -d "$(realpath "$1")" ]; then
                        yazi "$1"
                    else
                        bat --style=plain "$1"
                    fi
                else
                    if [ -d "$(realpath "$1")" ]; then
                        setsid $TERMINAL yazi "$1"
                    else
                        bat --style=plain "$1"
                    fi
                fi
                ;;
        esac
        ;;
    edit)
        case "$1" in
            *png|*jpg|*jpe|*jpeg|*gif|*webp)
                setsid gimp "$1" >/dev/null 2>&1 &
                ;;
            *mp3|*flac|*opus|*mp3?*|*flac?*|*opus?*|*wav)
                #handles both local and remote
                setsid audacity "$1" >/dev/null 2>&1 & ;;
            *pdf)
                setsid zathura "$1" & ;;
            *docx|*ppt|*pptx|*xls|*xlsx|*odt|*ods|*odp)
                setsid libreoffice "$1" & ;;
            *html|http*)
                $BROWSER "$1" & ;;
            *)
                if tty -s; then
                    nvim "$1"
                else
                    setsid $TERMINAL nvim "$1"
                fi
                ;;
        esac
        ;;
    download)
        mkdir -p /tmp/mediabuf && rm -rf /tmp/mediabuf/*
        cd /tmp/mediabuf
        case "$1" in
            *youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*)
                if yt-dlp "$1"; then
                    setsid mpv --input-ipc-server="/tmp/mpvsoc$(date +%s)" -quiet /tmp/mediabuf/* >/dev/null 2>&1 &
                fi
                ;;
            *mp3|*flac|*opus|*mp3?*|*flac?*|*opus?*|*mp4|*m4a|*mkv|*webm|*wav)
                wget "$1"
                setsid mpv --input-ipc-server="/tmp/mpvsoc$(date +%s)" /tmp/mediabuf/* >/dev/null 2>&1 &
                ;;
            *png|*jpg|*jpe|*jpeg|*gif|*webp)
                case "$1" in
                    http*)
                        wget "$1" -O image
                        setsid imv image >/dev/null 2>&1 & ;;
                    *)
                        setsid imv "$1" >/dev/null 2>&1 & ;;
                esac
                ;;
            *springer.com*)
                curl -sO "$(curl -s "$scihub$*" | grep -Po "(?<=location.href=').+.pdf")"
                setsid zathura ./*pdf & ;;
            *pdf)
                wget "$1"
                setsid zathura "$1" & ;;
            *)
                paplay ~/dotfiles/media/error.wav > /dev/null 2>/dev/null &
                ;;
        esac
        cd -
        ;;
    pi*)
        case "$1" in
            *mkv*|*webm*|*mp4*|*mp3*|*flac|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*|*gifv|*v.redd.it*|*gifs.com*)
               ~/lighthome/send.sh "home/command/videoplayer/$TARGET"
               ~/lighthome/send.sh --notify "home/command/video/$TARGET/play" "$1"
               ;;
            *png|*jpg|*JPG|*jpeg|*gif)
               ~/lighthome/send.sh "home/command/videoplayer/$TARGET"
               ~/lighthome/send.sh --notify "home/command/video/$TARGET/play" "$1"
               ;;
            *)
               paplay ~/dotfiles/media/error.wav > /dev/null 2>/dev/null &
               exit 1
               ;;
        esac
        ;;
    *)
        echo "Invalid target: $TARGET" >&1
        paplay ~/dotfiles/media/error.wav > /dev/null 2>/dev/null &
        exit 1
        ;;
esac;

