#!/bin/sh
source /etc/os-release
OPT=
case "$ID" in
    alpine|postmarketos)
        if [ "$1 " = "-i" ]; then
            OPT="--installed"
        fi
        pkg=$(apk list $OPT | sed -e "s/{.*}//g" -e "s/(.*)//g" -e "s/x86_64//g" -e "s/aarch64//g" | fzf)
        if [ -n "$pkg" ]; then
            pkgname="$(echo "$pkg" | cut -d" " -f 1 | sed -e "s/-[0-9].*$//g")"
            apk info "$pkgname"
            if echo "$pkg" | grep -q installed; then
                apk manifest "$pkgname"
            fi
        fi
        ;;
    *)
        echo "unknown OS" >&2
esac
