#!/bin/sh
. /etc/os-release
OPT=
case "$ID" in
    alpine|postmarketos)
        if [ "$1" = "-i" ]; then
            OPT="--installed"
        fi
        pkg=$(apk list $OPT | sed -e "s/{.*}//g" -e "s/(.*)//g" -e "s/x86_64//g" -e "s/aarch64//g" | fzf)
        if [ -n "$pkg" ]; then
            pkgname="$(echo "$pkg" | cut -d" " -f 1 | sed -e "s/-[0-9].*$//g")"
            apk info "$pkgname"
            if echo "$pkg" | grep -q installed; then
                echo "press enter for manifest"
                read -r _x && apk manifest "$pkgname"
            fi
        fi
        ;;
    arch)
        if [ "$1" = "-i" ]; then
            pkg=$(pacman -Q | fzf)
        else
            pkg=$(pacman -Ss | grep "^[a-z].*" | sed "s|[a-z]*/||" | fzf)
        fi
        if [ -n "$pkg" ]; then
            pkgname="$(echo "$pkg" | cut -d" " -f 1)"
            pacman -Qi "$pkgname"
            echo "press enter for manifest"
            read -r _x && pacman -Ql "$pkgname"
        fi
        ;;
    debian|ubuntu)
        if [ "$1" = "-i" ]; then
            OPT="-i"
        fi
        pkg=$(apt list $OPT | fzf)
        if [ -n "$pkg" ]; then
            pkgname="$(echo "$pkg" | sed 's|/.*$||')"
            apt show "$pkgname"
            echo "press enter for manifest (if installed)"
            read -r _x && dpkg -L "$pkgname"
        fi
        ;;
    *)
        echo "unknown OS" >&2
esac
