#!/bin/sh

# Start Tmux

sleep 1 #minor delay to allow river to read the title and move the window before tmux changes it
if [ -n "$1" ]; then
    if command -v "$1" 2> /dev/null && [ "$1" != "local" ]; then
        name=$1
    else
        name=$1
    fi
    shift
else
    name=untitled
fi
if [ $# -gt 0 ]; then
    tmux new -As "$name" "$*"
else
    tmux new -As "$name"
fi
